GenesisBlog/Models/BlogPost.cs
using GenesisBlog.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GenesisBlog.Models
{
    public partial class BlogPost
    {
        public int Id { get; set; }

        [Required]
        [StringLength(150, ErrorMessage ="The {0} must be at least {2} and at most {1} characters long",MinimumLength=5)]
        public string Title { get; set; } = "";

        [Required]
        public string Abstract { get; set; } = "";

        [Required]
        public string Content { get; set; } = "";

        [DataType(DataType.Date)]
        public DateTime Created { get; set; } = DateTime.UtcNow;

        public DateTime? Updated { get; set; }

        //This property is derived from the Title. This will eventually be used in some cases INSTEAD of the Primary Key (Id)              
        public string Slug { get; set; } = "";

        public bool IsDeleted { get; set; }

        public BlogPostState BlogPostState { get; set; }

        //What if I wanted to record an image with a blog post
        [Display(Name ="Choose Image")]
        public byte[] ImageData { get; set; } = Array.Empty<byte>();

        public string ImageType { get; set; } = string.Empty;

        [NotMapped]
        [Display(Name ="Choose an image")]
        public IFormFile? ImageFile { get; set; }

        //Nav props
        public virtual ICollection<BlogPostComment> BlogPostComments { get; set; } = new HashSet<BlogPostComment>();
        public virtual ICollection<Tag> Tags { get; set; } = new HashSet<Tag>();

    }
}

GenesisBlog/Controllers/BlogPostCommentsController.cs
#nullable disable
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GenesisBlog.Data;
using GenesisBlog.Models;
using Microsoft.AspNetCore.Identity;

namespace GenesisBlog.Controllers
{
    public class BlogPostCommentsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<BlogUser> _userManager;

        public BlogPostCommentsController(ApplicationDbContext context, UserManager<BlogUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: BlogPostComments
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.BlogPostComment.Include(b => b.BlogPost);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: BlogPostComments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blogPostComment = await _context.BlogPostComment
                .Include(b => b.BlogPost)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (blogPostComment == null)
            {
                return NotFound();
            }

            return View(blogPostComment);
        }

        // POST: BlogPostComments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BlogPostId,Comment")] BlogPostComment blogPostComment)
        {
            if (ModelState.IsValid)
            {
                blogPostComment.Created = DateTime.UtcNow;
                blogPostComment.AuthorId = _userManager.GetUserId(User);

                _context.Add(blogPostComment);
                await _context.SaveChangesAsync();              
                return RedirectToAction("Details", "BlogPosts", new { Id = blogPostComment.BlogPostId });

            }
            ViewData["BlogPostId"] = new SelectList(_context.BlogPost, "Id", "Abstract", blogPostComment.BlogPostId);
            return View(blogPostComment);
        }

        // GET: BlogPostComments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blogPostComment = await _context.BlogPostComment.FindAsync(id);
            if (blogPostComment == null)
            {
                return NotFound();
            }
            ViewData["BlogPostId"] = new SelectList(_context.BlogPost, "Id", "Abstract", blogPostComment.BlogPostId);
            return View(blogPostComment);
        }

        // POST: BlogPostComments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,BlogPostId,Comment")] BlogPostComment blogPostComment)
        {
            if (id != blogPostComment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(blogPostComment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BlogPostCommentExists(blogPostComment.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BlogPostId"] = new SelectList(_context.BlogPost, "Id", "Abstract", blogPostComment.BlogPostId);
            return View(blogPostComment);
        }

        // GET: BlogPostComments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blogPostComment = await _context.BlogPostComment
                .Include(b => b.BlogPost)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (blogPostComment == null)
            {
                return NotFound();
            }

            return View(blogPostComment);
        }

        // POST: BlogPostComments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var blogPostComment = await _context.BlogPostComment.FindAsync(id);
            _context.BlogPostComment.Remove(blogPostComment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BlogPostCommentExists(int id)
        {
            return _context.BlogPostComment.Any(e => e.Id == id);
        }
    }
}

GenesisBlog/Controllers/BlogPostsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GenesisBlog.Data;
using GenesisBlog.Models;
using GenesisBlog.Services;
using GenesisBlog.Services.Interfaces;
using GenesisBlog.Utilities;

namespace GenesisBlog.Controllers
{
    public class BlogPostsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IImageService _imageService;

        public BlogPostsController(ApplicationDbContext context, IImageService imageService)
        {
            _context = context;
            _imageService = imageService;
        }

        // GET: BlogPosts
        public async Task<IActionResult> Index()
        {
            //var posts = await _context.BlogPost.ToListAsync();
            var posts = await _context.BlogPost
                                                  .Include(b => b.Tags)
                                                  .ToListAsync();

            return View(posts);
        }

        // GET: BlogPosts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
       
            if (id == null)
            {
                return NotFound();
            }

            var blogPost = await _context.BlogPost 
                .Include(b => b.Tags)
                .Include(b => b.BlogPostComments)
                .ThenInclude(c => c.Author)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (blogPost == null)
            {
                return NotFound();
            }

            return View(blogPost);
        }

        // GET: BlogPosts/Create
        public IActionResult Create()
        {
            //1: What data does the select list contain
            //2. The property that gets transmitted to HttpPost
            //3. The property that gets shown to the user
            ViewData["TagIds"] = new MultiSelectList(_context.Tag, "Id", "Text");
          
            return View();
        }

        // POST: BlogPosts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title,Abstract,Content,BlogPostState,ImageFile")] BlogPost blogPost, List<int> tagIds)
        {
            if (ModelState.IsValid)
            {
                //Create a variable named slug and use the new SlugService....
                //var myService1 = new SlugService();         
                SlugService slugSvc = new();
                var slug = slugSvc.URLFriendly(blogPost.Title);
                if(_context.BlogPost.Any(b => b.Slug == slug))
                {
                    ModelState.AddModelError("Title", "The resultant Slug is a dupe");
                    ViewData["TagIds"] = new MultiSelectList(_context.Tag, "Id", "Text", tagIds);
                    return View(blogPost);
                }
                else
                {
                    blogPost.Slug = slug;
                }
             
                //Before I try interacting with the IFormFile
                //I should make sure it's present
                if (blogPost.ImageFile is not null)
                {
                    blogPost.ImageData = await _imageService.ConvertFileToByteArrayAsync(blogPost.ImageFile);
                    blogPost.ImageType = blogPost.ImageFile.ContentType;
                }

                //Associate any/all selected tags with the BlogPost
                foreach(var tagId in tagIds)
                {               
                    blogPost.Tags.Add(await _context.Tag.FindAsync(tagId));                
                }

                _context.Add(blogPost);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["TagIds"] = new MultiSelectList(_context.Tag, "Id", "Text", tagIds);
            return View(blogPost);
        }

        // GET: BlogPosts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blogPost = await _context.BlogPost
                                                      .Include(b => b.Tags)
                                                      .FirstOrDefaultAsync(b => b.Id == id);

            if (blogPost == null)
            {
                return NotFound();
            }

            //4th parameter in a multiSelect list is a List<int> representing the current selection
            var tagPks = blogPost.Tags.Select(b => b.Id).ToList();
            ViewData["TagIds"] = new MultiSelectList(_context.Tag, "Id", "Text", tagPks);

            return View(blogPost);
        }

        // POST: BlogPosts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Abstract,Content,BlogPostState,ImageFile")] BlogPost blogPost, List<int> tagIds)
        {
            if (id != blogPost.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //This code gets whats known as a "Tracked entity". By default, most LINQ
                    //statement that pull data from a DB are tracked. In fact, if you don't it tracked
                    //you have to use extra code to tell it so.. AsNoTracking()
                    var existingPost = await _context.BlogPost
                                                            .Include(b => b.Tags)                                                         
                                                            .FirstOrDefaultAsync(b => b.Id == blogPost.Id);

                    SlugService slugSvc = new();
                    var newSlug = slugSvc.URLFriendly(blogPost.Title);
                    if(newSlug != existingPost.Slug)
                    {
                        if (_context.BlogPost.Any(b => b.Slug == newSlug))
                        {
                            ModelState.AddModelError("Title", "The resultant Slug is a dupe");
                            ViewData["TagIds"] = new MultiSelectList(_context.Tag, "Id", "Text", tagIds);
                            return View(blogPost);
                        }                     
                    }

                    //Before I try interacting with the IFormFile
                    //I should make sure it's present
                    if (blogPost.ImageFile is not null)
                    {
                        blogPost.ImageData = await _imageService.ConvertFileToByteArrayAsync(blogPost.ImageFile);
                        blogPost.ImageType = blogPost.ImageFile.ContentType;
                    }

                    existingPost.Tags.Clear();             
                    await _context.SaveChangesAsync();

                    //Continue on making the requested user changes
                    //Since I already have a tracked entity named existingPost I will
                    //copy over the incoming form values
                    existingPost.Slug = newSlug;
                    existingPost.Updated = DateTime.UtcNow;
                    existingPost.Title = blogPost.Title;
                    existingPost.Abstract = blogPost.Abstract;
                    existingPost.Content = blogPost.Content;
                    existingPost.BlogPostState = blogPost.BlogPostState;
                 
                    //Add all the selected tags back
                    foreach (var tagId in tagIds)
                    {
                        existingPost.Tags.Add(await _context.Tag.FindAsync(tagId));
                    }

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BlogPostExists(blogPost.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }


            ViewData["TagIds"] = new MultiSelectList(_context.Tag, "Id", "Text", tagIds);
            return View(blogPost);
        }

        // GET: BlogPosts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blogPost = await _context.BlogPost
                .FirstOrDefaultAsync(m => m.Id == id);
            if (blogPost == null)
            {
                return NotFound();
            }

            return View(blogPost);
        }

        // POST: BlogPosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var blogPost = await _context.BlogPost.FindAsync(id);
            _context.BlogPost.Remove(blogPost);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BlogPostExists(int id)
        {
            return _context.BlogPost.Any(e => e.Id == id);
        }
    }
}

GenesisBlog/Views/BlogPosts/Create.cshtml
@using GenesisBlog.Models
@using GenesisBlog.Enums

@model BlogPost

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>BlogPost</h4>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Create" enctype="multipart/form-data">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group mb-3">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="Abstract" class="control-label"></label>               
                <textarea asp-for="Abstract" class="form-control" rows=5></textarea>
                <span asp-validation-for="Abstract" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="Content" class="control-label"></label>

                @*I am in the Create and am dealing with a new situation
                    I want to either simply have a hidden input to store my quill data
                    or I want to display the actual Content. *@                                           
                <div id="quillEditor">
                    @if (Model != null)
                    {                 
                        @Html.Raw(Model.Content);
                    }
                </div>

               <input type="hidden" asp-for="Content" />                          
                <span asp-validation-for="Content" class="text-danger"></span>
                
            </div>
        
            <div class="form-group mb-3">
                <label asp-for="BlogPostState" class="control-label"></label>
                <select asp-for="BlogPostState" class="form-control" asp-items="@Html.GetEnumSelectList<BlogPostState>()" ></select>
                <span asp-validation-for="BlogPostState" class="text-danger"></span>
            </div>

             <div class="form-group mb-3">
                <label asp-for="ImageFile" class="control-label"></label>
                <input asp-for="ImageFile" type="file" class="form-control" accept=".jpg,.png,.gif"/>           
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>

             <div class="form-group">
                <label asp-for="Tags" class="control-label"></label>
                <select  name="TagIds" class ="form-control" asp-items="ViewBag.TagIds" multiple></select>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GenesisBlog/Views/BlogPosts/Details.cshtml
@model BlogPost

@{
    ViewData["Title"] = "Details";
    ViewData["BlogPostTitle"] = Model.Title;  
    ViewData["Abstract"] = Model.Abstract;  
    ViewData["Created"] = Model.Created.ToString("MMM dd, yyyy");  
}

<!-- Post Content-->
<article class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                @Html.Raw(Model.Content)
            </div>
        </div>
        <div class="row row-cols-1 row-cols-md-4 g-4">
            @foreach(var tag in Model.Tags) 
            {                
                <div class="col">
                        <a class="btn btn-warning btn-outline-dark">@tag.Text</a>    
                </div>
            }
        </div>       
    </div>
</article>
   
<div>
    @if (User.Identity!.IsAuthenticated)
    {
        <form asp-controller="BlogPostComments" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>         
            <input type="hidden" name="BlogPostId" value="@Model.Id">

            <div class="form-group">
                <label class="control-label">Add Comment</label>
                <input name="Comment" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-dark w-100" />
            </div>
        </form>
    }
    else
    {
        <div class="row">
            <div class="col">
                <a asp-area="Identity" asp-page="/Account/Login" class="btn btn-warning btn-outline-dark w-100">Login to add a comment</a>
            </div>
        </div>
    }

    <hr />

    <div class="row row-cols-1 g-2">
        @foreach (var comment in Model.BlogPostComments.OrderByDescending(c => c.Created))
        {
            <div class="col card border border-1 border-dark mb-3">
                <div class="card-header">
                    Author: @comment.Author!.FullName
                </div>
               <div class="card-body">
                   @comment.Comment
               </div>

                 <div class="card-footer">
                    Created on: @comment.Created.ToString("MMM dd, yyyy")
                </div>
            </div>
        }
    </div>

</div>

<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

GenesisBlog/Views/BlogPosts/Edit.cshtml
@using GenesisBlog.Enums
@model GenesisBlog.Models.BlogPost

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>BlogPost</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
         
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Abstract" class="control-label"></label>
                <input asp-for="Abstract" class="form-control" />
                <span asp-validation-for="Abstract" class="text-danger"></span>
            </div>

              <div class="form-group mb-5">
                <label asp-for="Content" class="control-label"></label>
                <div id="quillEditor"></div>
                <span asp-validation-for="Content" class="text-danger"></span>
                <input type="hidden" asp-for="Content" />      
            </div>
        
           
            <div class="form-group">
                <label asp-for="BlogPostState" class="control-label"></label>
                <select asp-for="BlogPostState" class="form-control" asp-items="@Html.GetEnumSelectList<BlogPostState>()"></select>
                <span asp-validation-for="BlogPostState" class="text-danger"></span>
            </div>
        
             <div class="form-group mb-3">
                <label asp-for="ImageFile" class="control-label"></label>
                <input asp-for="ImageFile" type="file" class="form-control" accept=".jpg,.png,.gif"/>           
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Tags" class="control-label"></label>
                <select  name="TagIds" class ="form-control" asp-items="ViewBag.TagIds" multiple></select>
            </div>

  
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        //When the page loads copy the innerHTML of the hidden Content into Quill
        quill.container.firstChild.innerHTML = document.getElementById("Content").value;   
    </script>
}

GenesisBlog/Views/BlogPosts/Index.cshtml
@using GenesisBlog.Models
@using GenesisBlog.Services.Interfaces

@model IEnumerable<BlogPost>
@inject IImageService _imageService

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th></th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
             <th>  
                 @Html.DisplayNameFor(model => model.Tags)
             </th>
            <th>
                @Html.DisplayNameFor(model => model.Abstract)
            </th>     
            <th>
                @Html.DisplayNameFor(model => model.Slug)
            </th>     

            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @if(item.ImageData.Length > 0)
                {
                    <img src="@_imageService.ConvertByteArrayToFile(item.ImageData, item.ImageType)" class="img-fluid w-50">
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>

            <td>
                    @foreach(var tag in item.Tags )
                    {
                        @tag.Text<br>
                    }
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Abstract)
            </td>
         
            <td>
                  @Html.DisplayFor(modelItem => item.Slug)
            </td>
          
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>